# Generated by Django 3.2.9 on 2021-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211122_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporogrenci',
            name='roporTuru',
            field=models.CharField(choices=[('anket', 'Anket'), ('dıs', 'DİS'), ('not', 'Not Raporu')], max_length=10),
        ),
    ]
